### ISSUE TITLE
Force reload

### ISSUE THREAD

**Issue by lastant** [yaodingyd/react-flickity-component#125]
Is it possible to force reload? I tried using reloadOnUpdate, but it reloads on each state change, and I'd like to have more control, make it reload conditionally, at least being able to specify dependency values.

**Comment by gpoole** [comment]
I think the current behaviour of `reloadOnUpdate` is not totally what you'd expect. I've looked into it and there is a workaround I've suggested here to get it to act like you're describing:
https://github.com/yaodingyd/react-flickity-component/issues/147
