### ISSUE TITLE
Doesn't work well on Safari iOS 15

### ISSUE THREAD

**Issue by thangly98** [yaodingyd/react-flickity-component#129]
I can't seem to slide it

**Comment by dskelton-cos** [comment]
Issue raised in the flickity library too. https://github.com/metafizzy/flickity/issues/1177

**Comment by gregg-cbs** [comment]
This is potentially solved and can be closed.

I left a comment on the related ticket, right at the bottom:
https://github.com/metafizzy/flickity/issues/1177
