### ISSUE TITLE
Please i've been having issue using the flickityRef, i can't wrap my head around it

### ISSUE THREAD

**Issue by dnor-dev** [yaodingyd/react-flickity-component#131]
I'm using next js(typescript) and i'm trying to use a custom icon and assign the functionality to it
i'm seriously having a hard time with it and any help will be appreciated, thanks.

**Comment by alts1994** [comment]
This [response](https://github.com/yaodingyd/react-flickity-component/issues/85) helped me figure it out.

If you're using a functional approach, you need to create a ref outside of the Flickity component and then define it using FlickityRef. Once that's done you can access the `previous` and `next` methods to slide the Flickity component. 

```
const flkty = useRef(null);

function next() {
  dispatch(setAppIdle(false));
  flkty.current.next();
}

function prev() {
  dispatch(setAppIdle(false));
  flkty.current.previous();
}
 
... 

return (
  <div>
      <button type="button" onClick={prev}>
        Prev
      </button>
      
      <Flickity
        elementType="div"
        flickityRef={(carouselRef) => {
          flkty.current = carouselRef;
        }}
      >
        ...
      </Flickity>
        
      
      <button type="button" onClick={next}>
        Next
      </button>
  </div>
 )
```
