### ISSUE TITLE
Updating peer dependencies to support React v. 18

### ISSUE THREAD

**Issue by haase1020** [yaodingyd/react-flickity-component#135]
First of all, thank you for this package! I would like to continue using react-flickity-component in my project, but I am getting an error about an incorrect peer dependency when I try to upgrade to React v. 18. Is it possible to update peer dependencies to support React v. 18? I am more than happy to help in any way I can!

**Comment by yaodingyd** [comment]
PR  is welcome. Could you also verify it is working with react 18?

**Comment by haase1020** [comment]
Sounds good! I will submit a PR as soon as I verify that the code works with react 18.

**Comment by nathnhughes** [comment]
+1 for this 👍 

At first glance, it seems my issue is to do with `React` no longer including `children` in the default component props, so would need to integrate `PropsWithChildren`.

**Comment by PQPMath3ws** [comment]
Works in some days... Now, the error with react 18 persists again.

**Comment by j2is** [comment]
Ditto

**Comment by bogdanbpeterson** [comment]
`npm` refuses to install `react-flickity-component`, but yarn installs it, with error tho
![image](https://user-images.githubusercontent.com/66746788/198162910-9f28c2bb-d6bf-4796-9a50-f574e83e4adf.png)

It works perfectly with react > 18

**Comment by bogdanbpeterson** [comment]
Here's working app example https://showcase-rfc-with-react-18.vercel.app/
And repo https://github.com/bogdanbpeterson/showcase-rfc-with-react-18

**Comment by ogaguinaga** [comment]
Is there any news o this? i would like to use this package with react 18 🙂

**Comment by bogdanbpeterson** [comment]
> Is there any news o this? i would like to use this package with react 18 🙂

You can, install it with yarn, but it's not safe (haha, it's obvious, isn't it? 😂)

**Comment by ogaguinaga** [comment]
yeah... 😅  I meant more about this issue being merged and released

**Comment by yaodingyd** [comment]
PR welcome

**Comment by cooperwfloyd** [comment]
@bogdanbpeterson looks like your example is working great with React 18 — you could PR the changes that you made? Looking forward to using this with Next.js 13, as their minimum React version is 18.

**Comment by bogdanbpeterson** [comment]
@cooperwfloyd I changed literally nothing, just installed it using `yarn` instead of `npm`.
I don't even know what to change to create a PR 😅

**Comment by cooperwfloyd** [comment]
Haha 😆 thanks for the quick reply @bogdanbpeterson, good to know. Sounds to me then like it is just an issue with the newer NPM versions handling peer dependencies differently. If that is true, sounds like we are good to upgrade React here since it is working as expected, just need to get around the peer dependency issue. I can PR the React upgrade.

**Comment by cooperwfloyd** [comment]
Haha 😆 well thanks for the quick reply @bogdanbpeterson. My guess is that it is a conflict with the newer Node / NPM versions and how they check peer dependencies then. Thanks for the info 👍

**Comment by ogaguinaga** [comment]
is there any news on this PR?

**Comment by ogaguinaga** [comment]
Is there a reason why this is not moving anywhere? I would love to use this 😅  anything I can do to help and accelerate this process?

**Comment by cooperwfloyd** [comment]
@ogaguinaga someone just needs to PR the changes to make this library compatible with React 18 and recent Node versions without the use of `--legacy-peer-deps` during installation. If you want to move this forward and have the time you are welcome to PR those changes 👍

**Comment by yaodingyd** [comment]
v4.0.0 is released with react 18 support.

**Comment by bogdanbryzh** [comment]
yay, good news 🥳

**Comment by cooperwfloyd** [comment]
amazing! thank you so much @yaodingyd! fully ready now to make the upgrade to Next.js 13 💪
