### ISSUE TITLE
Error children with typescript

### ISSUE THREAD

**Issue by imnamnv** [yaodingyd/react-flickity-component#136]
```
<Flickity
            className={"carousel"} // default ''
            elementType={"div"} // default 'div'
            options={flickityOptions} // takes flickity options {}
            disableImagesLoaded={false} // default false
            reloadOnUpdate={false} // default false
          >
            {hightLightList}
</Flickity>
```
      I have a error with TypeScript:  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Flickity> & Readonly<Props>'.
      
      Thank you

**Comment by muinmundzir** [comment]
Have you solved it yet? I found some same issue too

> ```
> <Flickity
>             className={"carousel"} // default ''
>             elementType={"div"} // default 'div'
>             options={flickityOptions} // takes flickity options {}
>             disableImagesLoaded={false} // default false
>             reloadOnUpdate={false} // default false
>           >
>             {hightLightList}
> </Flickity>
> ```
> 
> ```
>   I have a error with TypeScript:  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Flickity> & Readonly<Props>'.
>   
>   Thank you
> ```

**Comment by yaodingyd** [comment]
[v3.6.3](https://www.npmjs.com/package/react-flickity-component/v/3.6.3) should fix it
