### ISSUE TITLE
v4 does not include TypeScript type definitions

### ISSUE THREAD

**Issue by gpoole** [yaodingyd/react-flickity-component#140]
In v3 the .d.ts files were included in the published module, but they seem to be missing in the updated version. This is the complete directory tree of `node_modules/react-flickity-component` after installing `@latest`:

```
node_modules/react-flickity-component
├── README.md
├── dist
│   ├── react-flickity-component.es.js
│   ├── react-flickity-component.es.js.map
│   ├── react-flickity-component.umd.js
│   └── react-flickity-component.umd.js.map
└── package.json

2 directories, 6 files
```

Type information is not available because of this issue.

**Comment by yaodingyd** [comment]
fixed in v4.0.3
