### ISSUE TITLE
typescript import

### ISSUE THREAD

**Issue by minhquan1313** [yaodingyd/react-flickity-component#149]
![image](https://github.com/yaodingyd/react-flickity-component/assets/20660062/4ccee895-08fd-4181-ad95-1659e99df7df)
I got this issue when importing it, I'm using vite react + swc
Here is my package json
![image](https://github.com/yaodingyd/react-flickity-component/assets/20660062/a4286c3c-3e8b-4400-8e4f-c22a99b4efcb)
and tsconfig
![image](https://github.com/yaodingyd/react-flickity-component/assets/20660062/4d30d648-72c0-437f-b019-b3f4af0c2a17)
![image](https://github.com/yaodingyd/react-flickity-component/assets/20660062/7f3cf460-e1b4-4e68-99a2-48f48bddf7ba)

**Comment by enzogoncalves** [comment]
@minhquan1313 could you solve this problem? if yes, please share your solution. I am having the same issue.

**Comment by AaronJY** [comment]
I've raised a PR to fix this! https://github.com/yaodingyd/react-flickity-component/pull/150 (pinging @enzogoncalves in case you're still struggling with this)

**Comment by yaodingyd** [comment]
v4.0.7 should fix this
