### ISSUE TITLE
Dragging Issue while dragging the non current item

### ISSUE THREAD

**Issue by rakeshnayak360** [yaodingyd/react-flickity-component#151]
When I drag the any item other than the current item, the slider is set back to the first item. 
Following options are set:
draggable: true,
cellAlign: 'left',
pageDots: false,
contain: true,
prevNextButtons: false,
accessibility: true,
asNavFor: 'classname'

**Comment by yaodingyd** [comment]
Feel free to reopen the issue with a codesandbox example
