### ISSUE TITLE
Installing React Flickity component with yarn automatically adds imageloaded as a peer dependency.

### ISSUE THREAD

**Issue by eduardfossas** [yaodingyd/react-flickity-component#155]
Hello, anyway to solve this?

Installing React Flickity component with yarn automatically adds imageloaded as a peer dependency.

**Comment by yaodingyd** [comment]
imageloaded is a dependency so this is intended
https://github.com/yaodingyd/react-flickity-component/blob/085792ac14fcea67afad5a163a8145a5ba603ef2/package.json#L40

**Comment by eduardfossas** [comment]
Yeah, I know. I am just writing that because for some reason during the build of a Next.js 14 project complained about not finding jQuery.
