### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by 0sserc** [yaodingyd/react-flickity-component#89]
This might not be related to this library, but as the flickity-fullscreen package hasn't been updated for a year, just decided to post here.

We are using flickity in one of our projects, and added the package for fullscreen [flickity-fullscreen](https://github.com/metafizzy/flickity-fullscreen), it had been working for a while, but like a month ago it suddenly stopped working, and when we call 
`this.flkty.toggleFullscreen();`

it returns:
`TypeError: _this2.flkty.toggleFullscreen is not a function`

As I said, it worked before, and we never changed our code

`this.flkty.previous();` or `this.flkty.next();` still work smoothly.

Any clues?

**Comment by yaodingyd** [comment]
The last release happened two months ago so I doubt it was our issue. Nevertheless  if you could provide a minimal sandbox to reproduce your issue I'm happy to help you debug.

**Comment by MontoyaAndres** [comment]
any solution about this?

**Comment by yaodingyd** [comment]
@MontoyaAndres  can u provide a sandbox?

**Comment by yaodingyd** [comment]
Free feel to reopen with a sandbox link

**Comment by BharathaanSukumaran** [comment]
Hi not sure if a solution to this has been discovered but the reason why this wasn't working is because the toggleFullscreen method has been removed. A similar effect can be achieved using the resize method
